export const ingredients = {
  categorias: [
    "Carbohidratos",
    "Vegetales",
    "Proteinas",
    "Grasas y aceites",
    "Lacteos",
    "Condimentos y especias",
  ],
  data: [
    [
      { id: 1, name: "Arroz", ico: "🍚" },
      { id: 2, name: "Pasta", ico: "🍝" },
      { id: 3, name: "Pan", ico: "🍞" },
      { id: 4, name: "Patatas", ico: "🥔" },
      { id: 5, name: "Quinoa", ico: "🍚" },
      { id: 6, name: "Fideos", ico: "🍜" },
      { id: 7, name: "Cuscús", ico: "🍢" },
    ],
    [
      { id: 8, name: "Cebolla", ico: "🧅" },
      { id: 9, name: "Ajo", ico: "🧄" },
      { id: 10, name: "Zanahoria", ico: "🥕" },
      { id: 11, name: "Apio", ico: "🌿" },
      { id: 12, name: "Pimiento", ico: "🌶️" },
      { id: 13, name: "Champiñones", ico: "🍄" },
      { id: 14, name: "Espinacas", ico: "🍃" },
      { id: 15, name: "Berenjena", ico: "🍆" },
      { id: 16, name: "Tomate", ico: "🍅" },
      { id: 17, name: "Calabacín", ico: "🥒" },
    ],
    [
      { id: 18, name: "Carne", ico: "🍖" },
      { id: 19, name: "Pescado y mariscos", ico: "🐟" },
      { id: 20, name: "Huevos", ico: "🥚" },
      { id: 21, name: "Tofu", ico: "🌱" },
      { id: 22, name: "Frijoles", ico: "🥫" },
    ],
    [
      { id: 23, name: "Aceite de oliva", ico: "🫒" },
      { id: 24, name: "Aceite vegetal", ico: "🌻" },
      { id: 25, name: "Mantequilla", ico: "🧈" },
      { id: 26, name: "Margarina", ico: "🧀" },
      { id: 27, name: "Aceitunas", ico: "🫑" },
      { id: 28, name: "Aguacate", ico: "🥑" },
    ],
    [
      { id: 29, name: "Leche", ico: "🥛" },
      { id: 30, name: "Queso", ico: "🧀" },
      { id: 31, name: "Yogur", ico: "🥣" },
      { id: 32, name: "Nata", ico: "🥛" },
      { id: 33, name: "Mantequilla", ico: "🧈" },
    ],
    [
      { id: 34, name: "Sal", ico: "🧂" },
      { id: 35, name: "Pimienta", ico: "🌶️" },
      { id: 36, name: "Hierbas frescas o secas", ico: "🌿" },
      { id: 37, name: "Especias molidas", ico: "🧂" },
      { id: 38, name: "Salsas", ico: "🍅" },
    ],
  ],
};
